# Assignment 2 - Numpy Array Operations


### Numpy functions

Numpy(Numerical Python) is a library consisting of multidimensional array objects and a large collection of high-level mathematical functions to operate on these arrays

- np.stack
- np.linalg.inv
- np.linalg.solve
- np.transpose
- np.ndarray.flatten


In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations-kumaragurubalan')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "kumaragurubalan16/numpy-array-operations-kumaragurubalan" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/kumaragurubalan16/numpy-array-operations-kumaragurubalan


'https://jovian.ml/kumaragurubalan16/numpy-array-operations-kumaragurubalan'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [5]:
# List of functions explained 
function1 = np.stack 
function2 = np.linalg.inv
function3 = np.linalg.solve
function4 = np.transpose
function5 = np.ndarray.flatten

## Function 1 - np.stack

To Join Sequence of arrays

In [6]:
# Example 1 - working 
a = np.array([1,2,3])
b = np.array([4,5,6])

In [7]:
np.stack((a,b),axis=0) # axis=0, row stack

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.stack((a,b),axis=1) # axis=1, Column stack

array([[1, 4],
       [2, 5],
       [3, 6]])

Joining sequence of arrays using axis=0 row wise and axis=1 column wise

In [9]:
# Example 2 - working
np.hstack((a,b)) # horizontal Stack

array([1, 2, 3, 4, 5, 6])

In [10]:
np.vstack((a,b)) # vertical Stack

array([[1, 2, 3],
       [4, 5, 6]])

Joining sequence of arrays using horizontal Stack and vertical Stack

In [11]:
# Example 3 - breaking (to illustrate when it breaks)
c = np.array([1,2,3])
d = np.array([[4,5,6],[7,8,9]])

np.column_stack((c,d))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

while joining sequence of arrays using column stack 'c' has 1d array and 'd' has 2d array. If both values are in 2d array, it will execute without error. If we use row stack it executes.

In [12]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "kumaragurubalan16/numpy-array-operations-kumaragurubalan" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/kumaragurubalan16/numpy-array-operations-kumaragurubalan


'https://jovian.ml/kumaragurubalan16/numpy-array-operations-kumaragurubalan'

## Function 2 - np.linalg.inv

Inverse of Matrix

In [13]:
# Example 1 - working
a = np.array([[2,4],[6,8]])

In [14]:
np.linalg.inv(a)

array([[-1.  ,  0.5 ],
       [ 0.75, -0.25]])

2 Dimensional array of Inverse Matrix

In [15]:
# Example 2 - working
b = np.array([[2,3,4],[4,5,6],[3,4,7]])

In [16]:
np.linalg.inv(b)

array([[-2.75,  1.25,  0.5 ],
       [ 2.5 , -0.5 , -1.  ],
       [-0.25, -0.25,  0.5 ]])

3 Dimensional array of Inverse Matrix

In [17]:
# Example 3 - breaking (to illustrate when it breaks)
c = np.array([[1,2,3,4]])

In [18]:
np.linalg.inv(c)

LinAlgError: Last 2 dimensions of the array must be square

Given example is 1 dimensional array. Array must be 2 dimension of square matrix.

In [19]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "kumaragurubalan16/numpy-array-operations-kumaragurubalan" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/kumaragurubalan16/numpy-array-operations-kumaragurubalan


'https://jovian.ml/kumaragurubalan16/numpy-array-operations-kumaragurubalan'

## Function 3 - np.linalg.solve

To solve linear algebra equation

In [20]:
# Example 1 - working
x = np.array([[3,1],[1,2]])
y = np.array([9,8])

In [21]:
np.linalg.solve(x,y)

array([2., 3.])

In [22]:
# Example 2 - working
x1 = np.array([[1,0,-3],[2,-1,2],[7,-3,-5]])
y1 = np.array([-5,16,19])

In [23]:
np.linalg.solve(x1,y1)

array([ 4., -2.,  3.])

In [24]:
# Example 3 - breaking (to illustrate when it breaks)
x2 = np.array([[2,4],[3,6]])
y2 = np.array([4,5,6])

In [25]:
np.linalg.solve(x2,y2)

ValueError: solve1: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m)->(m) (size 3 is different from 2)

Given example values of arrays x and y are different. 

In [26]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "kumaragurubalan16/numpy-array-operations-kumaragurubalan" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/kumaragurubalan16/numpy-array-operations-kumaragurubalan


'https://jovian.ml/kumaragurubalan16/numpy-array-operations-kumaragurubalan'

## Function 4 - np.transpose

Reverse of an array

In [27]:
# Example 1 - working
d = np.array([[2,3],[4,5]])

In [28]:
np.transpose(d)

array([[2, 4],
       [3, 5]])

2 Dimensional array of Reverse Matrix

In [29]:
# Example 2 - working
d1 = np.array([[2,3,4],[4,5,6],[3,4,7]])

In [30]:
np.transpose(d1)

array([[2, 4, 3],
       [3, 5, 4],
       [4, 6, 7]])

3 Dimensional array of Reverse Matrix

In [31]:
# Example 3 - breaking (to illustrate when it breaks)
np.transpose(d1,(1))

ValueError: axes don't match array

Given axes doesn't match array. It should be (1,0) or (0,1)

In [32]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "kumaragurubalan16/numpy-array-operations-kumaragurubalan" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/kumaragurubalan16/numpy-array-operations-kumaragurubalan


'https://jovian.ml/kumaragurubalan16/numpy-array-operations-kumaragurubalan'

## Function 5 - np.ndarray.flatten

It flattens the multi dimensional array into single dimensional array

In [33]:
# Example 1 - working
t=np.arange(8).reshape(2,2,2)
t

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [34]:
np.ndarray.flatten(t)

array([0, 1, 2, 3, 4, 5, 6, 7])

It flattens 2 Dimensional array into 1 Dimensional array

In [35]:
# Example 2 - working
t.flatten('F')

array([0, 4, 2, 6, 1, 5, 3, 7])

It flatten array using column based.

In [36]:
# Example 3 - breaking (to illustrate when it breaks)
t.flatten('D')

ValueError: order must be one of 'C', 'F', 'A', or 'K' (got 'D')

Given order must be one of 'C', 'F', 'A', or 'K'

In [37]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "kumaragurubalan16/numpy-array-operations-kumaragurubalan" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/kumaragurubalan16/numpy-array-operations-kumaragurubalan


'https://jovian.ml/kumaragurubalan16/numpy-array-operations-kumaragurubalan'

## Conclusion

Numpy functions - np.stack, np.linalg.inv ,np.linalg.solve ,np.transpose, np.ndarray.flatten

In [38]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "kumaragurubalan16/numpy-array-operations-kumaragurubalan" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/kumaragurubalan16/numpy-array-operations-kumaragurubalan


'https://jovian.ml/kumaragurubalan16/numpy-array-operations-kumaragurubalan'